#ifndef GUARD_CONSTANTS_QUEST_MENU_H
#define GUARD_CONSTANTS_QUEST_MENU_H

// Quest IDs for defeating each Gym Leader
#define QUEST_DEFEAT_ROXANNE       0
#define QUEST_DEFEAT_BRAWLY        1
#define QUEST_DEFEAT_WATTSON       2
#define QUEST_DEFEAT_FLANNERY      3
#define QUEST_DEFEAT_NORMAN        4
#define QUEST_DEFEAT_WINONA        5
#define QUEST_DEFEAT_TATE_AND_LIZA 6
#define QUEST_DEFEAT_JUAN          7

#define GYM_LEADER_QUEST_COUNT     8

// Rewards for completing each Gym Leader quest
#define QUEST_REWARD_ROXANNE       ITEM_MEGA_RING
#define QUEST_REWARD_BRAWLY        ITEM_TERA_ORB
#define QUEST_REWARD_WATTSON       ITEM_Z_POWER_RING
#define QUEST_REWARD_FLANNERY      ITEM_DYNAMAX_BAND
#define QUEST_REWARD_NORMAN        SPECIES_OGERPON
#define QUEST_REWARD_WINONA        SPECIES_OKIDOGI
#define QUEST_REWARD_TATE_AND_LIZA SPECIES_MUNKIDORI
#define QUEST_REWARD_JUAN          SPECIES_FEZANDIPITI

#endif // GUARD_CONSTANTS_QUEST_MENU_H