#ifndef GUARD_CONSTANTS_QUEST_MENU_H
#define GUARD_CONSTANTS_QUEST_MENU_H

// Actions for ScrCmd_questmenu
enum {
    QUEST_MENU_OPEN,
    QUEST_MENU_UNLOCK_QUEST,
    QUEST_MENU_SET_ACTIVE,
    QUEST_MENU_SET_REWARD,
    QUEST_MENU_COMPLETE_QUEST,
    QUEST_MENU_CHECK_UNLOCKED,
    QUEST_MENU_CHECK_ACTIVE,
    QUEST_MENU_CHECK_REWARD,
    QUEST_MENU_CHECK_COMPLETE,
    QUEST_MENU_BUFFER_QUEST_NAME,
};

// Flags for QuestMenu_GetSetQuestState
enum {
    FLAG_SET_UNLOCKED,
    FLAG_SET_ACTIVE,
    FLAG_SET_REWARD,
    FLAG_SET_COMPLETED,
    FLAG_REMOVE_ACTIVE,
    FLAG_REMOVE_REWARD,
    FLAG_GET_UNLOCKED,
    FLAG_GET_ACTIVE,
    FLAG_GET_REWARD,
    FLAG_GET_COMPLETED,
    FLAG_GET_INACTIVE,
};

#endif // GUARD_CONSTANTS_QUEST_MENU_H