gText_Creator_Welcome::
# 1 "data/text/birch_speech.pory"
	.string "{COLOR LIGHT_RED}Greetings, traveler. I am HERO SIGMA-\n"
	.string "the one who shaped this world.\p"
	.string "This is no ordinary journey.\n"
	.string "Legends stir across time and space…\l"
	.string "awakened by the Rift that tore our\l"
	.string "worlds apart.\p"
	.string "Here, you will walk among them,\n"
	.string "battle them, and uncover truths\l"
	.string "long buried.\p"
	.string "But remember… your choices will echo\n"
	.string "across regions. Your bonds with\l"
	.string "POKéMON will shape the fate of all\l"
	.string "creation.{COLOR WHITE}\p$"

gText_Birch_Welcome::
# 17 "data/text/birch_speech.pory"
	.string "{COLOR GREEN}Welcome to the world of POKéMON!\n"
	.string "I'm Professor BIRCH-field researcher.\p"
	.string "I study local POKéMON and I'm glad\n"
	.string "to finally meet you.{COLOR WHITE}\p$"

gText_Birch_Pokemon::
# 24 "data/text/birch_speech.pory"
	.string "{COLOR GREEN}This little one is a POKéMON-\n"
	.string "your partner and friend.{COLOR WHITE}\p$"

gText_Birch_MainSpeech::
# 29 "data/text/birch_speech.pory"
	.string "{COLOR GREEN}HOENN's been strange lately.\p"
	.string "Currents shift, skies shimmer…\n"
	.string "people whisper about 'rifts'.\p"
	.string "We observe, we protect, and when\n"
	.string "we must, we battle together.\p"
	.string "But first…{COLOR WHITE}\p$"

gText_Birch_AndYouAre::
# 38 "data/text/birch_speech.pory"
	.string "{COLOR GREEN}And you are?{COLOR WHITE}$"

gText_Birch_BoyOrGirl::
# 42 "data/text/birch_speech.pory"
	.string "{COLOR GREEN}Are you a boy, or a girl?{COLOR WHITE}$"

gText_Birch_WhatsYourName::
# 46 "data/text/birch_speech.pory"
	.string "{COLOR GREEN}All right-what's your name?{COLOR WHITE}$"

gText_Birch_SoItsPlayer::
# 50 "data/text/birch_speech.pory"
	.string "{COLOR GREEN}So it's {PLAYER}{KUN}?{COLOR WHITE}$"

gText_Birch_YourePlayer::
# 54 "data/text/birch_speech.pory"
	.string "{COLOR GREEN}All set… wait.\p"
	.string "It really is you, isn't it?\p"
	.string "Eight years since LITTLEROOT…\p"
	.string "HOENN's not normal right now.\n"
	.string "We'll talk when you arrive.\p"
	.string "Your mom said you're in town.\p"
	.string "Come to the lab, {PLAYER}.\n"
	.string "I'll be waiting.{COLOR WHITE}\p$"

gText_Birch_AreYouReady::
# 65 "data/text/birch_speech.pory"
	.string "{COLOR GREEN}Ready! Your journey begins now,\n"
	.string "{PLAYER}{KUN}!{COLOR WHITE}\p$"
