JubilifeCity_MapScripts::
	.byte 0

OreburghGate2F_MapScripts::
	.byte 0

OreburghCityA_MapScripts::
	.byte 0

SendOffSpring_MapScripts::
	.byte 0

LakeVerityCave_MapScripts::
	.byte 0

LakeValorCave_MapScripts::
	.byte 0

LakeAcuityCave_MapScripts::
	.byte 0

EternaForestA_MapScripts::
	.byte 0

EventScript_Whirlpool::
	end

RuinsOfAlph_PuzzleAndRewardChambers_MapScript_StatueDescription::
	end

AbandonedShip_CaptainsOffice_EventScript_ItemStorageKey::
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemLuxuryBall::
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemScanner::
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemTMRainDance::
	end

AbandonedShip_HiddenFloorRooms_EventScript_ItemWaterStone::
	end

AbandonedShip_Room_B1F_EventScript_ItemTMIceBeam::
	end

AbandonedShip_Rooms2_1F_EventScript_ItemRevive::
	end

AbandonedShip_Rooms2_B1F_EventScript_ItemDiveBall::
	end

AbandonedShip_Rooms_1F_EventScript_ItemHarborMail::
	end

AbandonedShip_Rooms_B1F_EventScript_ItemEscapeRope::
	end

AquaHideout_B1F_EventScript_ItemMasterBall::
	end

AquaHideout_B1F_EventScript_ItemMaxElixir::
	end

AquaHideout_B1F_EventScript_ItemNugget::
	end

AquaHideout_B2F_EventScript_ItemNestBall::
	end

ArtisanCave_1F_EventScript_ItemCarbos::
	end

ArtisanCave_B1F_EventScript_ItemHPUp::
	end

CeladonDeptElevator_EventScript_Elevator::
	end

CeruleanCity_Mart_EventScript_CooltrainerF::
	end

CeruleanCity_Mart_EventScript_Juggler::
	end

FieryPath_EventScript_ItemFireStone::
	end

FieryPath_EventScript_ItemTMToxic::
	end

FuchsiaCity_Mart_EventScript_Fisher::
	end

FuchsiaCity_Mart_EventScript_Woman::
	end

GoldenrodDeptElevator_EventScript_Elevator::
	end

GraniteCave_1F_EventScript_ItemEscapeRope::
	end

GraniteCave_B1F_EventScript_ItemPokeBall::
	end

GraniteCave_B2F_EventScript_ItemRareCandy::
	end

GraniteCave_B2F_EventScript_ItemRepel::
	end

JaggedPass_EventScript_ItemBurnHeal::
	end

LakeOfRageLowTide_EventScript_Sage::
	end

LavenderTown_Mart_EventScript_Pokefan::
	end

LavenderTown_Mart_EventScript_Rocker::
	end

LilycoveCity_EventScript_ItemMaxRepel::
	end

MagmaHideout_1F_EventScript_ItemRareCandy::
	end

MagmaHideout_2F_2R_EventScript_ItemFullRestore::
	end

MagmaHideout_2F_2R_EventScript_ItemMaxElixir::
	end

MagmaHideout_3F_1R_EventScript_ItemNugget::
	end

MagmaHideout_3F_2R_EventScript_ItemPPMax::
	end

MagmaHideout_3F_3R_EventScript_ItemEscapeRope::
	end

MagmaHideout_4F_EventScript_ItemMaxRevive::
	end

MahoganyTown_EventScript_TownTrigger::
	end

MauvilleCity_EventScript_ItemXSpeed::
	end

MauvilleCity_Gym_EventScript_Axle::
	end

MauvilleCity_Gym_EventScript_Cole::
	end

MauvilleCity_Gym_EventScript_Danielle::
	end

MauvilleCity_Gym_EventScript_Flannery::
	end

MauvilleCity_Gym_EventScript_Gerald::
	end

MeteorFalls_1F_1R_EventScript_ItemFullHeal::
	end

MeteorFalls_1F_1R_EventScript_ItemMoonStone::
	end

MeteorFalls_1F_1R_EventScript_ItemPPUP::
	end

MeteorFalls_1F_1R_EventScript_ItemTMIronTail::
	end

MeteorFalls_B1F_2R_EventScript_ItemTMDragonClaw::
	end

MossdeepCity_EventScript_ItemNetBall::
	end

MtPyre_2F_EventScript_ItemUltraBall::
	end

MtPyre_3F_EventScript_ItemSuperRepel::
	end

MtPyre_4F_EventScript_ItemSeaIncense::
	end

MtPyre_5F_EventScript_ItemLaxIncense::
	end

MtPyre_6F_EventScript_ItemTMShadowBall::
	end

MtPyre_Exterior_EventScript_ItemMaxPotion::
	end

MtPyre_Exterior_EventScript_ItemTMSkillSwap::
	end

NewMauville_Inside_EventScript_ItemEscapeRope::
	end

NewMauville_Inside_EventScript_ItemFullHeal::
	end

NewMauville_Inside_EventScript_ItemParalyzeHeal::
	end

NewMauville_Inside_EventScript_ItemThunderStone::
	end

NewMauville_Inside_EventScript_ItemUltraBall::
	end

OldaleTown_EventScript_RivalsHouseSign::
	end

OldaleTown_House1_EventScript_Rival::
	end

PetalburgCity_EventScript_ItemEther::
	end

PetalburgCity_EventScript_ItemMaxRevive::
	end

PetalburgCity_EventScript_NormanHouseSign::
	end

PetalburgWoods_EventScript_ItemEther::
	end

PetalburgWoods_EventScript_ItemGreatBall::
	end

PetalburgWoods_EventScript_ItemParalyzeHeal::
	end

PetalburgWoods_EventScript_ItemXAttack::
	end

PewterCity_Mart_EventScript_Nerd::
	end

PewterCity_Mart_EventScript_Youngster::
	end

Route101_EventScript_HelpMe::
	end

Route101_EventScript_ZigzagoonBattle::
	end

Route102_EventScript_ItemPotion::
	end

Route103_EventScript_ItemGuardSpec::
	end

Route103_EventScript_ItemPPUp::
	end

Route104_EventScript_ItemPPUp::
	end

Route104_EventScript_ItemPokeBall::
	end

Route104_EventScript_ItemPotion::
	end

Route104_EventScript_ItemXAccuracy::
	end

Route104_PrettyPetalFlowerShop_EventScript_MintOwner::
	end

Route105_EventScript_ItemIron::
	end

Route106_EventScript_ItemProtein::
	end

Route108_EventScript_ItemStarPiece::
	end

Route109_EventScript_ItemPPUp::
	end

Route109_EventScript_ItemPotion::
	end

Route110_EventScript_ItemDireHit::
	end

Route110_EventScript_ItemElixir::
	end

Route110_EventScript_ItemRareCandy::
	end

Route110_TrickHousePuzzle1_EventScript_ItemOrangeMail::
	end

Route110_TrickHousePuzzle2_EventScript_ItemHarborMail::
	end

Route110_TrickHousePuzzle2_EventScript_ItemWaveMail::
	end

Route110_TrickHousePuzzle3_EventScript_ItemShadowMail::
	end

Route110_TrickHousePuzzle3_EventScript_ItemWoodMail::
	end

Route110_TrickHousePuzzle4_EventScript_ItemMechMail::
	end

Route110_TrickHousePuzzle6_EventScript_ItemGlitterMail::
	end

Route110_TrickHousePuzzle7_EventScript_ItemTropicMail::
	end

Route110_TrickHousePuzzle8_EventScript_ItemBeadMail::
	end

Route111_EventScript_ItemElixir::
	end

Route111_EventScript_ItemHPUp::
	end

Route111_EventScript_ItemStardust::
	end

Route111_EventScript_ItemTMSandstorm::
	end

Route112_EventScript_ItemNugget::
	end

Route113_EventScript_ItemHyperPotion::
	end

Route113_EventScript_ItemMaxEther::
	end

Route113_EventScript_ItemSuperRepel::
	end

Route114_EventScript_ItemEnergyPowder::
	end

Route114_EventScript_ItemProtein::
	end

Route114_EventScript_ItemRareCandy::
	end

Route115_EventScript_ItemGreatBall::
	end

Route115_EventScript_ItemHealPowder::
	end

Route115_EventScript_ItemIron::
	end

Route115_EventScript_ItemPPUp::
	end

Route115_EventScript_ItemSuperPotion::
	end

Route115_EventScript_ItemTMFocusPunch::
	end

Route116_EventScript_ItemEther::
	end

Route116_EventScript_ItemHPUp::
	end

Route116_EventScript_ItemPotion::
	end

Route116_EventScript_ItemRepel::
	end

Route116_EventScript_ItemXSpecial::
	end

Route117_EventScript_ItemGreatBall::
	end

Route117_EventScript_ItemRevive::
	end

Route118_EventScript_ItemHyperPotion::
	end

Route119_EventScript_ItemElixir::
	end

Route119_EventScript_ItemElixir2::
	end

Route119_EventScript_ItemHyperPotion::
	end

Route119_EventScript_ItemHyperPotion2::
	end

Route119_EventScript_ItemLeafStone::
	end

Route119_EventScript_ItemNugget::
	end

Route119_EventScript_ItemRareCandy::
	end

Route119_EventScript_ItemSuperRepel::
	end

Route119_EventScript_ItemZinc::
	end

Route120_EventScript_ItemFullHeal::
	end

Route120_EventScript_ItemHyperPotion::
	end

Route120_EventScript_ItemNestBall::
	end

Route120_EventScript_ItemNugget::
	end

Route120_EventScript_ItemRevive::
	end

Route121_EventScript_ItemCarbos::
	end

Route121_EventScript_ItemRevive::
	end

Route121_EventScript_ItemZinc::
	end

Route123_EventScript_ItemCalcium::
	end

Route123_EventScript_ItemElixir::
	end

Route123_EventScript_ItemPPUp::
	end

Route123_EventScript_ItemRevivalHerb::
	end

Route123_EventScript_ItemUltraBall::
	end

Route124_EventScript_ItemBlueShard::
	end

Route124_EventScript_ItemRedShard::
	end

Route124_EventScript_ItemYellowShard::
	end

Route125_EventScript_ItemBigPearl::
	end

Route126_EventScript_ItemGreenShard::
	end

Route127_EventScript_ItemCarbos::
	end

Route127_EventScript_ItemRareCandy::
	end

Route127_EventScript_ItemZinc::
	end

Route132_EventScript_ItemProtein::
	end

Route132_EventScript_ItemRareCandy::
	end

Route133_EventScript_ItemBigPearl::
	end

Route133_EventScript_ItemMaxRevive::
	end

Route133_EventScript_ItemStarPiece::
	end

Route134_EventScript_ItemCarbos::
	end

Route134_EventScript_ItemStarPiece::
	end

Route34_EventScript_DaycareMan::
	end

Route47_EventScript_Chinchou::
	end

RuinsOfAlph_Lab_EventScript_FossilScientist::
	end

RustboroCity_EventScript_ItemXDefend::
	end

RustboroCity_Flat2_1F_EventScript_Chef::
	end

RusturfTunnel_EventScript_ItemMaxEther::
	end

RusturfTunnel_EventScript_ItemPokeBall::
	end

SafariZone_North_EventScript_ItemCalcium::
	end

SafariZone_Northeast_EventScript_ItemNugget::
	end

SafariZone_Northwest_EventScript_ItemTMSolarBeam::
	end

SafariZone_Southeast_EventScript_ItemBigPearl::
	end

SafariZone_Southwest_EventScript_ItemMaxRevive::
	end

SafronMart_EventScript_CooltrainerF::
	end

SafronMart_EventScript_CooltrainerM::
	end

ScorchedSlab_EventScript_ItemTMSunnyDay::
	end

SeafloorCavern_Room9_EventScript_ItemTMEarthquake::
	end

ShoalCave_LowTideEntranceRoom_EventScript_ItemBigPearl::
	end

ShoalCave_LowTideIceRoom_EventScript_ItemNeverMeltIce::
	end

ShoalCave_LowTideIceRoom_EventScript_ItemTMHail::
	end

ShoalCave_LowTideInnerRoom_EventScript_ItemRareCandy::
	end

ShoalCave_LowTideStairsRoom_EventScript_ItemIceHeal::
	end

VermilionCity_Mart_EventScript_BirdMan::
	end

VermilionCity_Mart_EventScript_Woman::
	end

VictoryRoad_1F_EventScript_ItemMaxElixir::
	end

VictoryRoad_1F_EventScript_ItemPPUp::
	end

VictoryRoad_B1F_EventScript_ItemFullRestore::
	end

VictoryRoad_B1F_EventScript_ItemTMPsychic::
	end

VictoryRoad_B2F_EventScript_ItemFullHeal::
	end

ViridianCity_Mart_EventScript_Cooltrainer::
	end

ViridianCity_Mart_EventScript_Lass::
	end
